#!/system/bin/sh

MODDIR=${0%/*}

USER_ID="user1"
OTP_URL="https://raw.githubusercontent.com/rootonly4-gif/OTP-MINE/main/${USER_ID}.txt"

sleep 20

while true; do

    log "🔄 Checking OTP for $USER_ID..."

    # Fetch OTP
    REMOTE_OTP=$(curl -m 5 -s "$OTP_URL" 2>/dev/null)

    # Check connection error
    if [ $? -ne 0 ]; then
        log "❌ ERROR: No connection"
        sleep 60
        continue
    fi

    # Clean value
    REMOTE_OTP=$(echo "$REMOTE_OTP" | tr -d '\r\n ')

    log "OTP=[$REMOTE_OTP]"

    # Empty check
    if [ -z "$REMOTE_OTP" ]; then
        log "❌ ERROR: EMPTY RESPONSE"
        sleep 60
        continue
    fi

    # Control logic
    if [ "$REMOTE_OTP" = "OFF" ]; then
        log "⛔ DISABLED"
        touch "$MODDIR/disable"
    else
        log "✅ ACTIVE"
        rm -f "$MODDIR/disable"
    fi

    sleep 60

done &
